DS-970: Add Magic Nix Cache and other workflow changes
DeterminateSystems/nix-installer-example pull request #11
Opened 2023-07-14 09:47 UTC by flexiondotorg

An assortment of GitHub Workflow changes, potentially including:

- Enable DeterminateSystems/magic-nix-cache-action@main
- Reference all DeterminateSystems actions via @main
- Make update.yaml consistent across repos
- Remove unnecessary github-token: from nix-installer-action
- Update actions/checkout@v2 to actions/checkout@v3

2023-07-14 16:29 UTC, Hoverbear requested changes

2023-07-14 16:29 UTC, Hoverbear commented on .github/workflows/ci.yml
> +      - uses: DeterminateSystems/magic-nix-cache-action@main
I don't think you intended to delete this line.

2023-07-24 14:04 UTC, flexiondotorg commented
@Hoverbear Thanks for the feedback. You're right; I didn't mean to delete the checkout :facepalm: I've pushed an update which returns the missing checkout step.

2023-07-24 15:08 UTC, Hoverbear approved these changes

2023-07-24 15:08 UTC, merged